[versions]
trove = "1.6.0+26.3"

[libraries]
trove-bom = { module = "me.roundaround:trove-bom", version.ref = "trove" }
trove-fabric-core = { module = "me.roundaround:trove-fabric-core" }
trove-neoforge-core = { module = "me.roundaround:trove-neoforge-core" }
trove-forge-core = { module = "me.roundaround:trove-forge-core" }
trove-config-gui = { module = "me.roundaround:trove-config-gui" }
trove-fabric-gametest = { module = "me.roundaround:trove-fabric-gametest" }
trove-neoforge-gametest = { module = "me.roundaround:trove-neoforge-gametest" }
trove-forge-gametest = { module = "me.roundaround:trove-forge-gametest" }
